[env:photopainter]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
board = esp32-s3-devkitc1-n16r8
framework = arduino
custom_app_version = 0.1.0
extra_scripts = pre:scripts/pio_set_ota_repo.py
lib_deps =
    bblanchon/ArduinoJson@^7
    adafruit/Adafruit GFX Library@^1.12.1
    lewisxhe/XPowersLib@^0.3.0
monitor_speed = 115200
board_build.flash_mode = qio
board_build.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi
build_flags =
    -DBOARD_HAS_PSRAM
    -DXPOWERS_CHIP_AXP2101
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DFW_VERSION=\"${this.custom_app_version}\"
    -DDEVICE_MODEL=\"photopainter\"
    -DOTA_FIRMWARE_ASSET_NAME=\"photopainter.bin\"
    ; -DENABLE_SERVER_LOGS
    ; -DDEBUG_LOGS
    ; -DFORCE_IMAGE_REFRESH_ON_WAKE
    ; -DFORCE_OTA_ON_NEXT_BOOT
